### ISSUE TITLE
Add homebrew formula

### ISSUE THREAD

**Issue by olivernybroe** [ohdearapp/ohdear-cli#31]
Would be cool if the ohdear cli could be installed directly via homebrew for make it easier for non-php developers to use it.

**Comment by freekmurze** [comment]
Feel free to PR installation instructions for the brew version to the readme of this package 👍

**Comment by owenvoke** [comment]
Just went to PR it to the core repository, looks like it doesn't have enough stars, etc. on GitHub to be in the main repo. Oh well, I'll PR install instructions later.

**Comment by freekmurze** [comment]
How many stars would it need?

**Comment by olivernybroe** [comment]
Oh so not only stars, it also need watchers and forks 🤔

**Comment by freekmurze** [comment]
I could try to get us to 75 stars. I'll tweet about it later today 🤞

**Comment by owenvoke** [comment]
https://github.com/Homebrew/homebrew-core/pull/102775 has been merged! GitHub Pages is [just built a deployment](https://github.com/Homebrew/formulae.brew.sh/runs/6753008926) and it's now live at https://formulae.brew.sh/formula/ohdear-cli 🤘🏻 🥳 I've [added install instructions to the README](https://github.com/ohdearapp/ohdear-cli/blob/main/README.md#install), and this issue can now be closed. 👍🏻

**Comment by freekmurze** [comment]
I tried it, but maybe I'm too early?

<img width="682" alt="CleanShot 2022-06-06 at 11 25 49@2x" src="https://user-images.githubusercontent.com/483853/172134237-1832871b-5a1b-4683-b958-3f944060475e.png">

**Comment by owenvoke** [comment]
Try a `brew update`? 🤔

**Comment by freekmurze** [comment]
Should have tried that before 🙂 

Added a note on this in the readme.
