### ISSUE TITLE
require(/var/www/vendor/composer/../ohdearapp/ohdear-cli/app/helpers.php): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by vincent-goossens** [ohdearapp/ohdear-cli#53]
Hi, getting this error when include this package, any idea?

`root@eba620ba0bdf:/var/www# php composer.phar require ohdearapp/ohdear-cli
Using version ^4.2 for ohdearapp/ohdear-cli
./composer.json has been updated
Running composer update ohdearapp/ohdear-cli
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking ohdearapp/ohdear-cli (v4.2.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading ohdearapp/ohdear-cli (v4.2.0)
  - Installing ohdearapp/ohdear-cli (v4.2.0): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Script Illuminate\Foundation\ComposerScripts::postAutoloadDump handling the post-autoload-dump event terminated with an exception

                                                                                                                               
  [ErrorException]                                                                                                             
  require(/var/www/vendor/composer/../ohdearapp/ohdear-cli/app/helpers.php): Failed to open stream: No such file or directory  `

<img width="895" alt="Screenshot 2024-04-10 at 08 31 35" src="https://github.com/ohdearapp/ohdear-cli/assets/11923607/a70aef2d-fe29-495d-8ec8-1510c6d03536">

**Comment by itguy614** [comment]
@vincent-goossens what was your resolution?  I am getting the same error.
