### ISSUE TITLE
Any idea how can I set the OHDEAR_API_TOKEN environment variable ?

### ISSUE THREAD

**Issue by vincent-goossens** [ohdearapp/ohdear-cli#54]
I am deploying via bitbucket pipeline and adding this package like this and:

![Screenshot 2024-04-10 at 09 18 57](https://github.com/ohdearapp/ohdear-cli/assets/11923607/43a1190b-0483-4238-9b03-db6042f9a989)

- step: &deploy-testing
        name: Deploy (Testing)
        deployment: Testing
        caches:
          - composer
        script:
          - apt-get update && apt-get install -qy unzip git libmcrypt-dev rsync
          - php src/composer.phar --version
          - php src/composer.phar global require ohdearapp/ohdear-cli
          - ~/.composer/vendor/bin/ohdear maintenance-period:start 52135 60 --OHDEAR_API_TOKEN=$OHDEAR_API_TOKEN
          - php src/composer.phar global require "laravel/envoy"
          - ~/.composer/vendor/bin/envoy run deploy-testing --host=$DEPLOY_HOST --user=$DEPLOY_USER --path=$DEPLOY_PATH --build=$BITBUCKET_BUILD_NUMBER --commit=$BITBUCKET_COMMIT --branch=$BITBUCKET_BRANCH --php=php8.1 --dir=$BITBUCKET_CLONE_DIR/src

**Comment by owenvoke** [comment]
Looking at your script, it seems like `$OHDEAR_API_TOKEN` might already be defined, so you should be able to just run the command as `~/.composer/vendor/bin/ohdear maintenance-period:start 52135 60`

**Comment by vincent-goossens** [comment]
I managed to add the env variable by doing: export OHDEAR_API_TOKEN=$OHDEAR_API_TOKEN

php src/composer.phar global require ohdearapp/ohdear-cli && export OHDEAR_API_TOKEN=$OHDEAR_API_TOKEN && ~/.composer/vendor/bin/ohdear maintenance-period:start $OHDEAR_SITE_ID 60 && php src/composer.phar global remove ohdearapp/ohdear-cli
